import { IAppMenu } from "@/types/model";

const projectCode = "project-code";
const current = new Date().toISOString();

export const reportMenuItems: IAppMenu[] = [
  {
    id: 1,
    project_code: projectCode,
    path: "/attendance/report/stock-in",
    name: "Báo cáo tồn đầu ca",
    icon: "Box",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-stock-in",
    parent_id: null,
    sort_order: 1,
    metadata: {},
    created_at: current,
    updated_at: current,
  },
  {
    id: 2,
    project_code: projectCode,
    path: "/attendance/report/sampling",
    name: "Báo cáo Sampling",
    icon: "StoragePool",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-sampling",
    parent_id: null,
    sort_order: 2,
    metadata: {},
    created_at: current,
    updated_at: current,
  },
  {
    id: 3,
    project_code: projectCode,
    path: "/attendance/report/stock-out",
    name: "Báo cáo tồn cuối ca",
    icon: "ReportData",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-stock-out",
    parent_id: null,
    sort_order: 3,
    metadata: {},
    created_at: current,
    updated_at: current,
  },
  {
    id: 4,
    project_code: projectCode,
    path: "/attendance/report/activity",
    name: "Báo cáo hoạt động",
    icon: "Image",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-activity",
    parent_id: null,
    sort_order: 4,
    metadata: {},
      created_at: current,
    updated_at: current,
  },
  {
    id: 4,
    project_code: projectCode,
    path: "/attendance/report/redeem",
    name: "Bán hàng tặng quà",
    icon: "ShoppingCart",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-redeem",
    parent_id: null,
    sort_order: 5,
    metadata: {},
    created_at: current,
    updated_at: current,
  },
  {
    id: 5,
    project_code: projectCode,
    path: "/attendance/report/survey",
    name: "Khảo sát",
    icon: "Customer",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-survey",
    parent_id: null,
    sort_order: 6,
    metadata: {},
    created_at: current,
    updated_at: current,
  },
  {
    id: 6,
    project_code: projectCode,
    path: "/attendance/report/customer",
    name: "Lịch sử khách hàng",
    icon: "RecentlyViewed",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-customer",
    parent_id: null,
    sort_order: 7,
    metadata: {},
    created_at: current,
    updated_at: current,
  },
  {
    id: 7,
    project_code: projectCode,
    path: "/attendance/report/gift",
    name: "Tặng quà",
    icon: "Gift",
    action_type: "route",
    action_value: "",
    menu_type: "APP",
    code: "report-gift",
    parent_id: null,
    sort_order: 8,
    metadata: {},
    created_at: current,
    updated_at: current,
  },
];
